### ISSUE TITLE
arp-validator unable to start

### ISSUE THREAD

**Issue by khoint0210** [rnehra01/arp-validator#1]
I'm unable to start every time I use 
`sudo ./arp-validator start -i eth0`
I'm using MacOS HS
it just shows the help table :(

**Comment by rnehra01** [comment]
Could you try `sudo ./arp-validator start -i eth0 -l /tmp/logs -d /tmp/hosts.json`? And there is no need to create the two `/tmp` files, they will be generated automatically.

**Comment by khoint0210** [comment]
oh thanks it work <3 it seem like I had to use all the option to make it work

**Comment by khoint0210** [comment]
`Error: Error: BIOCSETIF failed: Device not configured
    at Error (native)
    at new PcapSession (/Users/khoi123/arp-validator/node_modules/pcap/pcap.js:49:39)
    at Object.exports.createSession (/Users/khoi123/arp-validator/node_modules/pcap/pcap.js:123:12)
    at Object.startCapture (/Users/khoi123/arp-validator/lib/spoof-detector.js:124:25)
    at Object.<anonymous> (/Users/khoi123/arp-validator/app.js:2:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Error: Error: BIOCSETIF failed: Device not configured
    at Error (native)
    at new PcapSession (/Users/khoi123/arp-validator/node_modules/pcap/pcap.js:49:39)
    at Object.exports.createSession (/Users/khoi123/arp-validator/node_modules/pcap/pcap.js:123:12)
    at Object.startCapture (/Users/khoi123/arp-validator/lib/spoof-detector.js:124:25)
    at Object.<anonymous> (/Users/khoi123/arp-validator/app.js:2:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Error: Error: BIOCSETIF failed: Device not configured
    at Error (native)
    at new PcapSession (/Users/khoi123/arp-validator/node_modules/pcap/pcap.js:49:39)
    at Object.exports.createSession (/Users/khoi123/arp-validator/node_modules/pcap/pcap.js:123:12)
    at Object.startCapture (/Users/khoi123/arp-validator/lib/spoof-detector.js:124:25)
    at Object.<anonymous> (/Users/khoi123/arp-validator/app.js:2:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
`
I just open logs and saw this is t bad ????

**Comment by rnehra01** [comment]
Can you run `ifconfig` ? Usually in Mac, devices are named with en instead of eth0. For example, en0 and en1.

**Comment by khoint0210** [comment]
Oh, my bad <3 
![image](https://user-images.githubusercontent.com/12799726/33673526-8c05e940-dadf-11e7-995d-a04c5e862e24.png)
the log is because of those errors
